### ISSUE TITLE
Increase INITRD_SIZE size 

### ISSUE THREAD

**Issue by testriscv** [sysprog21/semu#62]
when increasing INITRD_SIZE (8 * 1024 * 1024) to (16 * 1024 * 1024) or more 128
and changing linux,initrd-start  
i.e.   linux,initrd-start =   <0x1F000000>;  
into minimal.dts 

always kernel panic with make check

**Comment by shengwen-tw** [comment]
You need to change the setting here also:
https://github.com/sysprog21/semu/blob/master/device.h#L10

**Comment by shengwen-tw** [comment]
Try `(511 - 16) * 1024 * 1024 = 0x1ef00000`

That is:
```c
chosen {
...
    linux,initrd-start = <0x1ef00000>; /* @495 MiB ((511 - 16) * 1024 * 1024)     */
    linux,initrd-end = <0x1fefffff>;   /* @511 MiB (511 * 1024 * 1024 - 1) */
};
```

**Comment by jserv** [comment]
@testriscv, Can you confirm if the suggestion of @shengwen-tw worked?

**Comment by testriscv** [comment]
thank you very much
