### ISSUE TITLE
virtio implementation in RVVM

### ISSUE THREAD

**Issue by ZLangJIT** [sysprog21/semu#63]
hi

i am currently attempting to port semu virtio into rvvm which currently lacks support for virtio

- https://github.com/LekKit/RVVM/issues/149

- specifically i would like help figuring out how to translate what https://github.com/LekKit/RVVM/issues/149#issuecomment-2393558104 (main.c , referenced by https://github.com/sysprog21/semu/pull/34 and https://github.com/shengwen-tw/semu/blob/bb98469f47b09324561970e91c49a58ab038a176/main.c) is doing in order to correctly set up virtio in semu

such that i can then begin replicating the same setup in rvvm with help from the RVVM maintainer as per the best way to go about such

for example

> Please see the RVVM API and only then try to adapt anything.
>
> Devices should not touch CPU specifics directly, like load/store instruction opcodes, registers. Devices should not trap the CPU manually either, it is done by the MMU subsystem.
>
> If semu project did it that way it's silly and should not be replicated here.

_Originally posted by @LekKit in https://github.com/LekKit/RVVM/issues/149#issuecomment-2393536320_

**Comment by shengwen-tw** [comment]
Hi,

I understand that you're interested in porting `semu`'s VirtIO implementations to `RVVM`. However, I'm unclear about the specific objectives you’d like to discuss.

Could you please clarify the specific information you would like to know?

**Comment by ZLangJIT** [comment]
> Hi,
> 
> I understand that you're interested in porting `semu`'s VirtIO implementations to `RVVM`. However, I'm unclear about the specific objectives you’d like to discuss.
> 
> Could you please clarify the specific information you would like to know?

in regards to the implementation detail of virtio and semu

basically if semu did not have virtio (more specifically if virtio was not "hooked into" semu at all) and you where adding virtio to semu how exactly would you do such on a step-by-step api-level

for example, something like `"first we register MMIO stuff with xyz semu api and pass it xyz from virtio api xyz,    then we register an interupt handler with xyz semu api xyz and pass it xyz from virtio api xyz..."`   and so on

with such we could begin figuring out what the equivilant RVVM api's/infastructure would be for each step of semu and adapt it to RVVM

**Comment by shengwen-tw** [comment]
> > Hi,
> > I understand that you're interested in porting `semu`'s VirtIO implementations to `RVVM`. However, I'm unclear about the specific objectives you’d like to discuss.
> > Could you please clarify the specific information you would like to know?
> 
> in regards to the implementation detail of virtio and semu
> 
> basically if semu did not have virtio (more specifically if virtio was not "hooked into" semu at all) and you where adding virtio to semu how exactly would you do such on a step-by-step api-level
> 
> for example, something like `"first we register MMIO stuff with xyz semu api and pass it xyz from virtio api xyz, then we register an interupt handler with xyz semu api xyz and pass it xyz from virtio api xyz..."` and so on
> 
> with such we could begin figuring out what the equivilant RVVM api's/infastructure would be for each step of semu and adapt it to RVVM

You may want to check [device.h](https://github.com/sysprog21/semu/blob/master/device.h) for the exposing APIs to the sub-systems for handling MMIO and interrupts of RV32 in semu.

Additionally, [VirtIO Committee Specification](https://docs.oasis-open.org/virtio/virtio/v1.2/csd01/virtio-v1.2-csd01.html) is useful for tracing and understanding the VirtIO implementation in semu.

**Comment by ZLangJIT** [comment]
im not sure if that helps, as the spec covers quite a lot and doesnt exactly specify in what order things should be implemented, ei it does not specify that implementation foo depends on an implementation of bar

**Comment by jserv** [comment]
I close this issue due to inactivity. Since VirtIO support for semu is still in development, it may not be suitable for RVVM integration at this time.
